//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.ParamDay", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineParamDay : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string CodingField;
    
    private System.DateTime InputDateField;
    
    private string KeyField;
    
    private string LanguageField;
    
    private string LocationIDField;
    
    private string UserField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Coding
    {
        get
        {
            return this.CodingField;
        }
        set
        {
            this.CodingField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime InputDate
    {
        get
        {
            return this.InputDateField;
        }
        set
        {
            this.InputDateField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Key
    {
        get
        {
            return this.KeyField;
        }
        set
        {
            this.KeyField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Language
    {
        get
        {
            return this.LanguageField;
        }
        set
        {
            this.LanguageField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string LocationID
    {
        get
        {
            return this.LocationIDField;
        }
        set
        {
            this.LocationIDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string User
    {
        get
        {
            return this.UserField;
        }
        set
        {
            this.UserField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.ResultDay", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineResultDay : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string CopyrightField;
    
    private string ErrMsgField;
    
    private string HtmlField;
    
    private string LangField;
    
    private EngineLocationInfo PlaceField;
    
    private EngineDateInfo TimeField;
    
    private ZmnType ZmanField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Copyright
    {
        get
        {
            return this.CopyrightField;
        }
        set
        {
            this.CopyrightField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ErrMsg
    {
        get
        {
            return this.ErrMsgField;
        }
        set
        {
            this.ErrMsgField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Html
    {
        get
        {
            return this.HtmlField;
        }
        set
        {
            this.HtmlField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Lang
    {
        get
        {
            return this.LangField;
        }
        set
        {
            this.LangField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public EngineLocationInfo Place
    {
        get
        {
            return this.PlaceField;
        }
        set
        {
            this.PlaceField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public EngineDateInfo Time
    {
        get
        {
            return this.TimeField;
        }
        set
        {
            this.TimeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public ZmnType Zman
    {
        get
        {
            return this.ZmanField;
        }
        set
        {
            this.ZmanField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.LocationInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineLocationInfo : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string AirportCodeField;
    
    private ushort CandlelightingMinutesField;
    
    private string CityField;
    
    private string CityHebrewField;
    
    private string CountryField;
    
    private string CountyField;
    
    private System.DateTime CurrentTimeField;
    
    private int DavenDirectionGCField;
    
    private int DavenDirectionRLField;
    
    private int ElevationEastField;
    
    private int ElevationObserverField;
    
    private int ElevationWestField;
    
    private string LocationIDField;
    
    private string NameField;
    
    private string NameHtmlField;
    
    private string NameShortField;
    
    private string ObservesDSTField;
    
    private string PostalCodeField;
    
    private string StateField;
    
    private double YakirDegreesDefaultField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string AirportCode
    {
        get
        {
            return this.AirportCodeField;
        }
        set
        {
            this.AirportCodeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public ushort CandlelightingMinutes
    {
        get
        {
            return this.CandlelightingMinutesField;
        }
        set
        {
            this.CandlelightingMinutesField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string City
    {
        get
        {
            return this.CityField;
        }
        set
        {
            this.CityField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string CityHebrew
    {
        get
        {
            return this.CityHebrewField;
        }
        set
        {
            this.CityHebrewField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Country
    {
        get
        {
            return this.CountryField;
        }
        set
        {
            this.CountryField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string County
    {
        get
        {
            return this.CountyField;
        }
        set
        {
            this.CountyField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime CurrentTime
    {
        get
        {
            return this.CurrentTimeField;
        }
        set
        {
            this.CurrentTimeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int DavenDirectionGC
    {
        get
        {
            return this.DavenDirectionGCField;
        }
        set
        {
            this.DavenDirectionGCField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int DavenDirectionRL
    {
        get
        {
            return this.DavenDirectionRLField;
        }
        set
        {
            this.DavenDirectionRLField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ElevationEast
    {
        get
        {
            return this.ElevationEastField;
        }
        set
        {
            this.ElevationEastField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ElevationObserver
    {
        get
        {
            return this.ElevationObserverField;
        }
        set
        {
            this.ElevationObserverField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ElevationWest
    {
        get
        {
            return this.ElevationWestField;
        }
        set
        {
            this.ElevationWestField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string LocationID
    {
        get
        {
            return this.LocationIDField;
        }
        set
        {
            this.LocationIDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string NameHtml
    {
        get
        {
            return this.NameHtmlField;
        }
        set
        {
            this.NameHtmlField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string NameShort
    {
        get
        {
            return this.NameShortField;
        }
        set
        {
            this.NameShortField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ObservesDST
    {
        get
        {
            return this.ObservesDSTField;
        }
        set
        {
            this.ObservesDSTField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string PostalCode
    {
        get
        {
            return this.PostalCodeField;
        }
        set
        {
            this.PostalCodeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string State
    {
        get
        {
            return this.StateField;
        }
        set
        {
            this.StateField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public double YakirDegreesDefault
    {
        get
        {
            return this.YakirDegreesDefaultField;
        }
        set
        {
            this.YakirDegreesDefaultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.DateInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineDateInfo : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string DafYomiField;
    
    private string DafYomiPageField;
    
    private string DafYomiTractField;
    
    private System.DateTime DateCivilField;
    
    private string DateCivilLongField;
    
    private string DateFullLongField;
    
    private string DateFullShortField;
    
    private string DateJewishField;
    
    private string DateJewishLongField;
    
    private string DateJewishShortField;
    
    private string DateSemiLongField;
    
    private string DateSemiShortField;
    
    private int DaylightTimeField;
    
    private string HolidayField;
    
    private string HolidayShortField;
    
    private bool IsAsaraBitevesField;
    
    private bool IsCholHamoedField;
    
    private bool IsErevPesachField;
    
    private bool IsErevShabbosField;
    
    private bool IsErevTishaBavField;
    
    private bool IsErevYomKipperField;
    
    private bool IsErevYomTovField;
    
    private bool IsFastDayField;
    
    private bool IsRoshChodeshField;
    
    private bool IsShabbosField;
    
    private bool IsShivaAsarBitammuzField;
    
    private bool IsTaanisEstherField;
    
    private bool IsTishaBavField;
    
    private bool IsTuBeshvatField;
    
    private bool IsTzomGedaliaField;
    
    private bool IsYomKipperField;
    
    private bool IsYomTovField;
    
    private int OmerField;
    
    private string ParshaField;
    
    private string ParshaAndHolidayField;
    
    private string ParshaShortField;
    
    private bool TomorrowNightIsYomTovField;
    
    private string TomorrowParshaField;
    
    private string TomorrowParshaOrHolidayField;
    
    private bool TonightIsYomTovField;
    
    private string WeekdayField;
    
    private string WeekdayShortField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DafYomi
    {
        get
        {
            return this.DafYomiField;
        }
        set
        {
            this.DafYomiField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DafYomiPage
    {
        get
        {
            return this.DafYomiPageField;
        }
        set
        {
            this.DafYomiPageField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DafYomiTract
    {
        get
        {
            return this.DafYomiTractField;
        }
        set
        {
            this.DafYomiTractField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DateCivil
    {
        get
        {
            return this.DateCivilField;
        }
        set
        {
            this.DateCivilField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateCivilLong
    {
        get
        {
            return this.DateCivilLongField;
        }
        set
        {
            this.DateCivilLongField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateFullLong
    {
        get
        {
            return this.DateFullLongField;
        }
        set
        {
            this.DateFullLongField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateFullShort
    {
        get
        {
            return this.DateFullShortField;
        }
        set
        {
            this.DateFullShortField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateJewish
    {
        get
        {
            return this.DateJewishField;
        }
        set
        {
            this.DateJewishField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateJewishLong
    {
        get
        {
            return this.DateJewishLongField;
        }
        set
        {
            this.DateJewishLongField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateJewishShort
    {
        get
        {
            return this.DateJewishShortField;
        }
        set
        {
            this.DateJewishShortField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateSemiLong
    {
        get
        {
            return this.DateSemiLongField;
        }
        set
        {
            this.DateSemiLongField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateSemiShort
    {
        get
        {
            return this.DateSemiShortField;
        }
        set
        {
            this.DateSemiShortField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int DaylightTime
    {
        get
        {
            return this.DaylightTimeField;
        }
        set
        {
            this.DaylightTimeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Holiday
    {
        get
        {
            return this.HolidayField;
        }
        set
        {
            this.HolidayField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string HolidayShort
    {
        get
        {
            return this.HolidayShortField;
        }
        set
        {
            this.HolidayShortField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsAsaraBiteves
    {
        get
        {
            return this.IsAsaraBitevesField;
        }
        set
        {
            this.IsAsaraBitevesField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsCholHamoed
    {
        get
        {
            return this.IsCholHamoedField;
        }
        set
        {
            this.IsCholHamoedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsErevPesach
    {
        get
        {
            return this.IsErevPesachField;
        }
        set
        {
            this.IsErevPesachField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsErevShabbos
    {
        get
        {
            return this.IsErevShabbosField;
        }
        set
        {
            this.IsErevShabbosField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsErevTishaBav
    {
        get
        {
            return this.IsErevTishaBavField;
        }
        set
        {
            this.IsErevTishaBavField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsErevYomKipper
    {
        get
        {
            return this.IsErevYomKipperField;
        }
        set
        {
            this.IsErevYomKipperField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsErevYomTov
    {
        get
        {
            return this.IsErevYomTovField;
        }
        set
        {
            this.IsErevYomTovField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsFastDay
    {
        get
        {
            return this.IsFastDayField;
        }
        set
        {
            this.IsFastDayField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsRoshChodesh
    {
        get
        {
            return this.IsRoshChodeshField;
        }
        set
        {
            this.IsRoshChodeshField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsShabbos
    {
        get
        {
            return this.IsShabbosField;
        }
        set
        {
            this.IsShabbosField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsShivaAsarBitammuz
    {
        get
        {
            return this.IsShivaAsarBitammuzField;
        }
        set
        {
            this.IsShivaAsarBitammuzField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsTaanisEsther
    {
        get
        {
            return this.IsTaanisEstherField;
        }
        set
        {
            this.IsTaanisEstherField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsTishaBav
    {
        get
        {
            return this.IsTishaBavField;
        }
        set
        {
            this.IsTishaBavField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsTuBeshvat
    {
        get
        {
            return this.IsTuBeshvatField;
        }
        set
        {
            this.IsTuBeshvatField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsTzomGedalia
    {
        get
        {
            return this.IsTzomGedaliaField;
        }
        set
        {
            this.IsTzomGedaliaField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsYomKipper
    {
        get
        {
            return this.IsYomKipperField;
        }
        set
        {
            this.IsYomKipperField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsYomTov
    {
        get
        {
            return this.IsYomTovField;
        }
        set
        {
            this.IsYomTovField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int Omer
    {
        get
        {
            return this.OmerField;
        }
        set
        {
            this.OmerField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Parsha
    {
        get
        {
            return this.ParshaField;
        }
        set
        {
            this.ParshaField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ParshaAndHoliday
    {
        get
        {
            return this.ParshaAndHolidayField;
        }
        set
        {
            this.ParshaAndHolidayField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ParshaShort
    {
        get
        {
            return this.ParshaShortField;
        }
        set
        {
            this.ParshaShortField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool TomorrowNightIsYomTov
    {
        get
        {
            return this.TomorrowNightIsYomTovField;
        }
        set
        {
            this.TomorrowNightIsYomTovField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string TomorrowParsha
    {
        get
        {
            return this.TomorrowParshaField;
        }
        set
        {
            this.TomorrowParshaField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string TomorrowParshaOrHoliday
    {
        get
        {
            return this.TomorrowParshaOrHolidayField;
        }
        set
        {
            this.TomorrowParshaOrHolidayField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool TonightIsYomTov
    {
        get
        {
            return this.TonightIsYomTovField;
        }
        set
        {
            this.TonightIsYomTovField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Weekday
    {
        get
        {
            return this.WeekdayField;
        }
        set
        {
            this.WeekdayField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string WeekdayShort
    {
        get
        {
            return this.WeekdayShortField;
        }
        set
        {
            this.WeekdayShortField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ZmnType", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct ZmnType : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private System.DateTime CandlesField;
    
    private System.DateTime ChametzBurnGraField;
    
    private System.DateTime ChametzBurnMA72Field;
    
    private System.DateTime ChametzBurnMA72fixField;
    
    private System.DateTime ChametzBurnRMFField;
    
    private System.DateTime ChametzEatGraField;
    
    private System.DateTime ChametzEatMA72Field;
    
    private System.DateTime ChametzEatMA72fixField;
    
    private System.DateTime ChametzEatRMFField;
    
    private System.DateTime CurrentTimeField;
    
    private System.DateTime Dawn72Field;
    
    private System.DateTime Dawn72fixField;
    
    private System.DateTime Dawn90Field;
    
    private System.DateTime DawnRMFField;
    
    private System.DateTime KetanaGraField;
    
    private System.DateTime KetanaMA72fixField;
    
    private System.DateTime MiddayField;
    
    private System.DateTime MiddayRMFField;
    
    private System.DateTime MidnightField;
    
    private System.DateTime Mincha30fixField;
    
    private System.DateTime MinchaGraField;
    
    private System.DateTime MinchaMA72fixField;
    
    private System.DateTime MinchaStrictField;
    
    private System.DateTime Night50fixField;
    
    private System.DateTime Night60fixField;
    
    private System.DateTime Night72Field;
    
    private System.DateTime Night72fixField;
    
    private System.DateTime Night72fixLevelField;
    
    private System.DateTime Night90Field;
    
    private System.DateTime NightChazonIshField;
    
    private System.DateTime NightFastRMFField;
    
    private System.DateTime NightFastTucField;
    
    private System.DateTime NightGra180Field;
    
    private System.DateTime NightGra225Field;
    
    private System.DateTime NightGra240Field;
    
    private System.DateTime NightMoedField;
    
    private System.DateTime NightShabbosField;
    
    private System.DateTime NightZalmanField;
    
    private System.DateTime PlagBenIsh72ToFastTucField;
    
    private System.DateTime PlagBenIsh72ToShabbosField;
    
    private System.DateTime PlagBenIsh90ToFastTucField;
    
    private System.DateTime PlagGraField;
    
    private System.DateTime PlagMA72fixField;
    
    private long PropBenIsh72ToFastTucField;
    
    private long PropBenIsh72ToShabbosField;
    
    private long PropBenIsh90ToFastTucField;
    
    private long PropGraField;
    
    private long PropMA72Field;
    
    private long PropMA72fixField;
    
    private long PropMA90Field;
    
    private long PropRmfMorningField;
    
    private System.DateTime ShachrisGraField;
    
    private System.DateTime ShachrisMA72Field;
    
    private System.DateTime ShachrisMA72fixField;
    
    private System.DateTime ShachrisMA90Field;
    
    private System.DateTime ShachrisRMFField;
    
    private System.DateTime ShemaBenIsh72ToFastTucField;
    
    private System.DateTime ShemaBenIsh72ToShabbosField;
    
    private System.DateTime ShemaBenIsh90ToFastTucField;
    
    private System.DateTime ShemaGraField;
    
    private System.DateTime ShemaMA72Field;
    
    private System.DateTime ShemaMA72fixField;
    
    private System.DateTime ShemaMA90Field;
    
    private System.DateTime ShemaRMFField;
    
    private System.DateTime SunriseDefaultField;
    
    private System.DateTime SunriseElevatedField;
    
    private System.DateTime SunriseLevelField;
    
    private System.DateTime SunsetDefaultField;
    
    private System.DateTime SunsetElevatedField;
    
    private System.DateTime SunsetLevelField;
    
    private System.DateTime Tomorrow2Night72fixField;
    
    private System.DateTime Tomorrow2NightChazonIshField;
    
    private System.DateTime Tomorrow2NightShabbosField;
    
    private System.DateTime Tomorrow2SunsetDefaultField;
    
    private System.DateTime Tomorrow2SunsetElevatedField;
    
    private System.DateTime Tomorrow2SunsetLevelField;
    
    private System.DateTime TomorrowNight72fixField;
    
    private System.DateTime TomorrowNightChazonIshField;
    
    private System.DateTime TomorrowNightShabbosField;
    
    private System.DateTime TomorrowSunriseDefaultField;
    
    private System.DateTime TomorrowSunriseElevatedField;
    
    private System.DateTime TomorrowSunriseLevelField;
    
    private System.DateTime TomorrowSunsetDefaultField;
    
    private System.DateTime TomorrowSunsetElevatedField;
    
    private System.DateTime TomorrowSunsetLevelField;
    
    private System.DateTime Yakir102Field;
    
    private System.DateTime Yakir110Field;
    
    private System.DateTime Yakir115Field;
    
    private System.DateTime YakirDefaultField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Candles
    {
        get
        {
            return this.CandlesField;
        }
        set
        {
            this.CandlesField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ChametzBurnGra
    {
        get
        {
            return this.ChametzBurnGraField;
        }
        set
        {
            this.ChametzBurnGraField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ChametzBurnMA72
    {
        get
        {
            return this.ChametzBurnMA72Field;
        }
        set
        {
            this.ChametzBurnMA72Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ChametzBurnMA72fix
    {
        get
        {
            return this.ChametzBurnMA72fixField;
        }
        set
        {
            this.ChametzBurnMA72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ChametzBurnRMF
    {
        get
        {
            return this.ChametzBurnRMFField;
        }
        set
        {
            this.ChametzBurnRMFField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ChametzEatGra
    {
        get
        {
            return this.ChametzEatGraField;
        }
        set
        {
            this.ChametzEatGraField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ChametzEatMA72
    {
        get
        {
            return this.ChametzEatMA72Field;
        }
        set
        {
            this.ChametzEatMA72Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ChametzEatMA72fix
    {
        get
        {
            return this.ChametzEatMA72fixField;
        }
        set
        {
            this.ChametzEatMA72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ChametzEatRMF
    {
        get
        {
            return this.ChametzEatRMFField;
        }
        set
        {
            this.ChametzEatRMFField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime CurrentTime
    {
        get
        {
            return this.CurrentTimeField;
        }
        set
        {
            this.CurrentTimeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Dawn72
    {
        get
        {
            return this.Dawn72Field;
        }
        set
        {
            this.Dawn72Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Dawn72fix
    {
        get
        {
            return this.Dawn72fixField;
        }
        set
        {
            this.Dawn72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Dawn90
    {
        get
        {
            return this.Dawn90Field;
        }
        set
        {
            this.Dawn90Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DawnRMF
    {
        get
        {
            return this.DawnRMFField;
        }
        set
        {
            this.DawnRMFField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime KetanaGra
    {
        get
        {
            return this.KetanaGraField;
        }
        set
        {
            this.KetanaGraField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime KetanaMA72fix
    {
        get
        {
            return this.KetanaMA72fixField;
        }
        set
        {
            this.KetanaMA72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Midday
    {
        get
        {
            return this.MiddayField;
        }
        set
        {
            this.MiddayField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime MiddayRMF
    {
        get
        {
            return this.MiddayRMFField;
        }
        set
        {
            this.MiddayRMFField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Midnight
    {
        get
        {
            return this.MidnightField;
        }
        set
        {
            this.MidnightField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Mincha30fix
    {
        get
        {
            return this.Mincha30fixField;
        }
        set
        {
            this.Mincha30fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime MinchaGra
    {
        get
        {
            return this.MinchaGraField;
        }
        set
        {
            this.MinchaGraField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime MinchaMA72fix
    {
        get
        {
            return this.MinchaMA72fixField;
        }
        set
        {
            this.MinchaMA72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime MinchaStrict
    {
        get
        {
            return this.MinchaStrictField;
        }
        set
        {
            this.MinchaStrictField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Night50fix
    {
        get
        {
            return this.Night50fixField;
        }
        set
        {
            this.Night50fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Night60fix
    {
        get
        {
            return this.Night60fixField;
        }
        set
        {
            this.Night60fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Night72
    {
        get
        {
            return this.Night72Field;
        }
        set
        {
            this.Night72Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Night72fix
    {
        get
        {
            return this.Night72fixField;
        }
        set
        {
            this.Night72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Night72fixLevel
    {
        get
        {
            return this.Night72fixLevelField;
        }
        set
        {
            this.Night72fixLevelField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Night90
    {
        get
        {
            return this.Night90Field;
        }
        set
        {
            this.Night90Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightChazonIsh
    {
        get
        {
            return this.NightChazonIshField;
        }
        set
        {
            this.NightChazonIshField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightFastRMF
    {
        get
        {
            return this.NightFastRMFField;
        }
        set
        {
            this.NightFastRMFField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightFastTuc
    {
        get
        {
            return this.NightFastTucField;
        }
        set
        {
            this.NightFastTucField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightGra180
    {
        get
        {
            return this.NightGra180Field;
        }
        set
        {
            this.NightGra180Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightGra225
    {
        get
        {
            return this.NightGra225Field;
        }
        set
        {
            this.NightGra225Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightGra240
    {
        get
        {
            return this.NightGra240Field;
        }
        set
        {
            this.NightGra240Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightMoed
    {
        get
        {
            return this.NightMoedField;
        }
        set
        {
            this.NightMoedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightShabbos
    {
        get
        {
            return this.NightShabbosField;
        }
        set
        {
            this.NightShabbosField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime NightZalman
    {
        get
        {
            return this.NightZalmanField;
        }
        set
        {
            this.NightZalmanField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime PlagBenIsh72ToFastTuc
    {
        get
        {
            return this.PlagBenIsh72ToFastTucField;
        }
        set
        {
            this.PlagBenIsh72ToFastTucField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime PlagBenIsh72ToShabbos
    {
        get
        {
            return this.PlagBenIsh72ToShabbosField;
        }
        set
        {
            this.PlagBenIsh72ToShabbosField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime PlagBenIsh90ToFastTuc
    {
        get
        {
            return this.PlagBenIsh90ToFastTucField;
        }
        set
        {
            this.PlagBenIsh90ToFastTucField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime PlagGra
    {
        get
        {
            return this.PlagGraField;
        }
        set
        {
            this.PlagGraField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime PlagMA72fix
    {
        get
        {
            return this.PlagMA72fixField;
        }
        set
        {
            this.PlagMA72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public long PropBenIsh72ToFastTuc
    {
        get
        {
            return this.PropBenIsh72ToFastTucField;
        }
        set
        {
            this.PropBenIsh72ToFastTucField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public long PropBenIsh72ToShabbos
    {
        get
        {
            return this.PropBenIsh72ToShabbosField;
        }
        set
        {
            this.PropBenIsh72ToShabbosField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public long PropBenIsh90ToFastTuc
    {
        get
        {
            return this.PropBenIsh90ToFastTucField;
        }
        set
        {
            this.PropBenIsh90ToFastTucField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public long PropGra
    {
        get
        {
            return this.PropGraField;
        }
        set
        {
            this.PropGraField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public long PropMA72
    {
        get
        {
            return this.PropMA72Field;
        }
        set
        {
            this.PropMA72Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public long PropMA72fix
    {
        get
        {
            return this.PropMA72fixField;
        }
        set
        {
            this.PropMA72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public long PropMA90
    {
        get
        {
            return this.PropMA90Field;
        }
        set
        {
            this.PropMA90Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public long PropRmfMorning
    {
        get
        {
            return this.PropRmfMorningField;
        }
        set
        {
            this.PropRmfMorningField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShachrisGra
    {
        get
        {
            return this.ShachrisGraField;
        }
        set
        {
            this.ShachrisGraField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShachrisMA72
    {
        get
        {
            return this.ShachrisMA72Field;
        }
        set
        {
            this.ShachrisMA72Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShachrisMA72fix
    {
        get
        {
            return this.ShachrisMA72fixField;
        }
        set
        {
            this.ShachrisMA72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShachrisMA90
    {
        get
        {
            return this.ShachrisMA90Field;
        }
        set
        {
            this.ShachrisMA90Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShachrisRMF
    {
        get
        {
            return this.ShachrisRMFField;
        }
        set
        {
            this.ShachrisRMFField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShemaBenIsh72ToFastTuc
    {
        get
        {
            return this.ShemaBenIsh72ToFastTucField;
        }
        set
        {
            this.ShemaBenIsh72ToFastTucField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShemaBenIsh72ToShabbos
    {
        get
        {
            return this.ShemaBenIsh72ToShabbosField;
        }
        set
        {
            this.ShemaBenIsh72ToShabbosField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShemaBenIsh90ToFastTuc
    {
        get
        {
            return this.ShemaBenIsh90ToFastTucField;
        }
        set
        {
            this.ShemaBenIsh90ToFastTucField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShemaGra
    {
        get
        {
            return this.ShemaGraField;
        }
        set
        {
            this.ShemaGraField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShemaMA72
    {
        get
        {
            return this.ShemaMA72Field;
        }
        set
        {
            this.ShemaMA72Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShemaMA72fix
    {
        get
        {
            return this.ShemaMA72fixField;
        }
        set
        {
            this.ShemaMA72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShemaMA90
    {
        get
        {
            return this.ShemaMA90Field;
        }
        set
        {
            this.ShemaMA90Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ShemaRMF
    {
        get
        {
            return this.ShemaRMFField;
        }
        set
        {
            this.ShemaRMFField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime SunriseDefault
    {
        get
        {
            return this.SunriseDefaultField;
        }
        set
        {
            this.SunriseDefaultField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime SunriseElevated
    {
        get
        {
            return this.SunriseElevatedField;
        }
        set
        {
            this.SunriseElevatedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime SunriseLevel
    {
        get
        {
            return this.SunriseLevelField;
        }
        set
        {
            this.SunriseLevelField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime SunsetDefault
    {
        get
        {
            return this.SunsetDefaultField;
        }
        set
        {
            this.SunsetDefaultField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime SunsetElevated
    {
        get
        {
            return this.SunsetElevatedField;
        }
        set
        {
            this.SunsetElevatedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime SunsetLevel
    {
        get
        {
            return this.SunsetLevelField;
        }
        set
        {
            this.SunsetLevelField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Tomorrow2Night72fix
    {
        get
        {
            return this.Tomorrow2Night72fixField;
        }
        set
        {
            this.Tomorrow2Night72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Tomorrow2NightChazonIsh
    {
        get
        {
            return this.Tomorrow2NightChazonIshField;
        }
        set
        {
            this.Tomorrow2NightChazonIshField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Tomorrow2NightShabbos
    {
        get
        {
            return this.Tomorrow2NightShabbosField;
        }
        set
        {
            this.Tomorrow2NightShabbosField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Tomorrow2SunsetDefault
    {
        get
        {
            return this.Tomorrow2SunsetDefaultField;
        }
        set
        {
            this.Tomorrow2SunsetDefaultField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Tomorrow2SunsetElevated
    {
        get
        {
            return this.Tomorrow2SunsetElevatedField;
        }
        set
        {
            this.Tomorrow2SunsetElevatedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Tomorrow2SunsetLevel
    {
        get
        {
            return this.Tomorrow2SunsetLevelField;
        }
        set
        {
            this.Tomorrow2SunsetLevelField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowNight72fix
    {
        get
        {
            return this.TomorrowNight72fixField;
        }
        set
        {
            this.TomorrowNight72fixField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowNightChazonIsh
    {
        get
        {
            return this.TomorrowNightChazonIshField;
        }
        set
        {
            this.TomorrowNightChazonIshField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowNightShabbos
    {
        get
        {
            return this.TomorrowNightShabbosField;
        }
        set
        {
            this.TomorrowNightShabbosField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowSunriseDefault
    {
        get
        {
            return this.TomorrowSunriseDefaultField;
        }
        set
        {
            this.TomorrowSunriseDefaultField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowSunriseElevated
    {
        get
        {
            return this.TomorrowSunriseElevatedField;
        }
        set
        {
            this.TomorrowSunriseElevatedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowSunriseLevel
    {
        get
        {
            return this.TomorrowSunriseLevelField;
        }
        set
        {
            this.TomorrowSunriseLevelField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowSunsetDefault
    {
        get
        {
            return this.TomorrowSunsetDefaultField;
        }
        set
        {
            this.TomorrowSunsetDefaultField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowSunsetElevated
    {
        get
        {
            return this.TomorrowSunsetElevatedField;
        }
        set
        {
            this.TomorrowSunsetElevatedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TomorrowSunsetLevel
    {
        get
        {
            return this.TomorrowSunsetLevelField;
        }
        set
        {
            this.TomorrowSunsetLevelField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Yakir102
    {
        get
        {
            return this.Yakir102Field;
        }
        set
        {
            this.Yakir102Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Yakir110
    {
        get
        {
            return this.Yakir110Field;
        }
        set
        {
            this.Yakir110Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime Yakir115
    {
        get
        {
            return this.Yakir115Field;
        }
        set
        {
            this.Yakir115Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime YakirDefault
    {
        get
        {
            return this.YakirDefaultField;
        }
        set
        {
            this.YakirDefaultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.ParamGps", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineParamGps : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string CodingField;
    
    private string KeyField;
    
    private EngineCoordinates PointField;
    
    private string UserField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Coding
    {
        get
        {
            return this.CodingField;
        }
        set
        {
            this.CodingField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Key
    {
        get
        {
            return this.KeyField;
        }
        set
        {
            this.KeyField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public EngineCoordinates Point
    {
        get
        {
            return this.PointField;
        }
        set
        {
            this.PointField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string User
    {
        get
        {
            return this.UserField;
        }
        set
        {
            this.UserField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.Coordinates", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineCoordinates : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private double LatField;
    
    private double LonField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public double Lat
    {
        get
        {
            return this.LatField;
        }
        set
        {
            this.LatField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public double Lon
    {
        get
        {
            return this.LonField;
        }
        set
        {
            this.LonField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.ResultGps", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineResultGps : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string ErrMsgField;
    
    private string LocationIDField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ErrMsg
    {
        get
        {
            return this.ErrMsgField;
        }
        set
        {
            this.ErrMsgField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string LocationID
    {
        get
        {
            return this.LocationIDField;
        }
        set
        {
            this.LocationIDField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.ParamPostal", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineParamPostal : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string CodingField;
    
    private string KeyField;
    
    private string QueryField;
    
    private double TimeZoneField;
    
    private string UserField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Coding
    {
        get
        {
            return this.CodingField;
        }
        set
        {
            this.CodingField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Key
    {
        get
        {
            return this.KeyField;
        }
        set
        {
            this.KeyField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Query
    {
        get
        {
            return this.QueryField;
        }
        set
        {
            this.QueryField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public double TimeZone
    {
        get
        {
            return this.TimeZoneField;
        }
        set
        {
            this.TimeZoneField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string User
    {
        get
        {
            return this.UserField;
        }
        set
        {
            this.UserField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Engine.ResultPostal", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial struct EngineResultPostal : System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string ErrMsgField;
    
    private string LocationIDField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ErrMsg
    {
        get
        {
            return this.ErrMsgField;
        }
        set
        {
            this.ErrMsgField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string LocationID
    {
        get
        {
            return this.LocationIDField;
        }
        set
        {
            this.LocationIDField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEngine")]
public interface IEngine
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngine/GetDay", ReplyAction="http://tempuri.org/IEngine/GetDayResponse")]
    EngineResultDay GetDay(EngineParamDay Param);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngine/GetDay", ReplyAction="http://tempuri.org/IEngine/GetDayResponse")]
    System.Threading.Tasks.Task<EngineResultDay> GetDayAsync(EngineParamDay Param);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngine/SearchGps", ReplyAction="http://tempuri.org/IEngine/SearchGpsResponse")]
    EngineResultGps SearchGps(EngineParamGps Param);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngine/SearchGps", ReplyAction="http://tempuri.org/IEngine/SearchGpsResponse")]
    System.Threading.Tasks.Task<EngineResultGps> SearchGpsAsync(EngineParamGps Param);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngine/SearchPostal", ReplyAction="http://tempuri.org/IEngine/SearchPostalResponse")]
    EngineResultPostal SearchPostal(EngineParamPostal Param);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngine/SearchPostal", ReplyAction="http://tempuri.org/IEngine/SearchPostalResponse")]
    System.Threading.Tasks.Task<EngineResultPostal> SearchPostalAsync(EngineParamPostal Param);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEngineChannel : IEngine, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EngineClient : System.ServiceModel.ClientBase<IEngine>, IEngine
{
    
    public EngineClient()
    {
    }
    
    public EngineClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EngineClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EngineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EngineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public EngineResultDay GetDay(EngineParamDay Param)
    {
        return base.Channel.GetDay(Param);
    }
    
    public System.Threading.Tasks.Task<EngineResultDay> GetDayAsync(EngineParamDay Param)
    {
        return base.Channel.GetDayAsync(Param);
    }
    
    public EngineResultGps SearchGps(EngineParamGps Param)
    {
        return base.Channel.SearchGps(Param);
    }
    
    public System.Threading.Tasks.Task<EngineResultGps> SearchGpsAsync(EngineParamGps Param)
    {
        return base.Channel.SearchGpsAsync(Param);
    }
    
    public EngineResultPostal SearchPostal(EngineParamPostal Param)
    {
        return base.Channel.SearchPostal(Param);
    }
    
    public System.Threading.Tasks.Task<EngineResultPostal> SearchPostalAsync(EngineParamPostal Param)
    {
        return base.Channel.SearchPostalAsync(Param);
    }
}
